import React from "react";
import { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import Button from "../components/Button";

const loadingText = () => {
  const Element = () => <p>Loading...</p>;
  return Element;
};

const Map = dynamic(() => import("../components/Map"), {
  loading: loadingText(),
  ssr: false,
});
const initPos = {
  x: 129.073532,
  y: 32.967488,
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button label="あいうえお" url="http://google.com" />
      <Map center={[initPos.x, initPos.y]} zoom={11} />
    </div>
  );
};

export default Home;
